extends Node

var customers: Dictionary = {
	"Ali": load("res://assets/customers/customer_ali.png"),
	"Boss": load("res://assets/customers/customer_boss.png"),
	"Melan": load("res://assets/customers/customer_melan.png"),
	"Kenz": load("res://assets/customers/customer_kenz.png"),
	"Kraze": load("res://assets/customers/customer_kraze.png"),
	"Mordekaiser": load("res://assets/customers/customer_mordekaiser.png"),
	"Miku": load("res://assets/customers/customer_miku.png"),
	"Carton": load("res://assets/customers/customer_carton.png"),
	"Chekered": load("res://assets/customers/customer_chekered.png"),
	"Soda": load("res://assets/customers/customer_soda.png"),
	"Rev": load("res://assets/customers/customer_rev.png"),
	"Kaori": load("res://assets/customers/customer_kaori.png"),
	"Ash": load("res://assets/customers/customer_ash.png"),
	"Cake Box": load("res://assets/TEMPCUSTOMER.png"),
}

var dialogue_icons: Dictionary = {
	"Ali": load("res://assets/dialogue_icons/dialogue_ali.png"),
	"Anje": load("res://assets/dialogue_icons/dialogue_anje.png"),
	"Boss": load("res://assets/dialogue_icons/dialogue_boss.png"),
	"Melan": load("res://assets/dialogue_icons/dialogue_melan.png"),
	"Kenz": load("res://assets/dialogue_icons/dialogue_kenz.png"),
	"Kraze": load("res://assets/dialogue_icons/dialogue_kraze.png"),
	"Mordekaiser": load("res://assets/dialogue_icons/dialogue_mordekaiser.png"),
	"Miku": load("res://assets/dialogue_icons/dialogue_miku.png"),
	"Carton": load("res://assets/dialogue_icons/dialogue_carton.png"),
	"Chekered": load("res://assets/dialogue_icons/dialogue_chekered.png"),
	"Horse": load("res://assets/dialogue_icons/dialogue_horse.png"),
	"Cow": load("res://assets/dialogue_icons/dialogue_cow.png"),
	
}

var interactables: Dictionary = {
	"Basket": load("res://assets/interactables/interactable_basket.png"),
	"Cabinet": load("res://assets/interactables/interactable_cabinet.png"),
	"Fridge": load("res://assets/interactables/interactable_fridge.png"),
	"Sink": load("res://assets/interactables/interactable_sink.png"),
	"Bread Proofer": load("res://assets/interactables/interactable_bread_proofer.png"),
	"Oven": load("res://assets/interactables/interactable_oven.png"),
	"Stand Mixer": load("res://assets/interactables/interactable_stand_mixer.png"),
	"Shelf": load("res://assets/interactables/interactable_shelf.png"),
	"Table": load("res://assets/interactables/interactable_table.png"),
	"Trash": load("res://assets/interactables/interactable_trash.png"),
}

var items: Dictionary = {
	"Bowl": load("res://assets/items/item_empty_bowl.png"),
	"Empty Bowl": load("res://assets/items/item_empty_bowl.png"),
	"Filled Bowl": load("res://assets/items/item_filled_bowl.png"),
	"Plain Cookies": load("res://assets/items/item_plain_cookies.png"),
	"Butter Cookies": load("res://assets/items/item_butter_cookies.png"),
	"Cheese Cookies": load("res://assets/items/item_cheese_cookies.png"),
	"Chocolate Chip Cookies": load("res://assets/items/item_chocolate_chip_cookies.png"),
	"Sugar Cookies": load("res://assets/items/item_sugar_cookies.png"),
	"Almond Cookies": load("res://assets/items/item_almond_cookies.png"),
	"Chocolate Crinkles": load("res://assets/items/item_chocolate_crinkles.png"),
	"Ube Crinkles": load("res://assets/items/item_ube_crinkles.png"),
	"Banana Bread": load("res://assets/items/item_banana_bread.png"),
	"Coco Bread": load("res://assets/items/item_coco_bread.png"),
	"Pandesal": load("res://assets/items/item_pandesal.png"),
	"Cheese Pandesal": load("res://assets/items/item_cheese_pandesal.png"),
	"Ube Pandesal": load("res://assets/items/item_ube_pandesal.png"),
	"Banana": load("res://assets/items/ingredient_banana.png"),
	"Coconut": load("res://assets/items/ingredient_coconut.png"),
	"Almonds": load("res://assets/items/ingredient_almonds.png"),
	"Ube": load("res://assets/items/ingredient_ube.png"),
	"Butter": load("res://assets/items/ingredient_butter.png"),
	"Cheese": load("res://assets/items/ingredient_cheese.png"),
	"Eggs": load("res://assets/items/ingredient_eggs.png"),
	"Milk": load("res://assets/items/ingredient_milk.png"),
	"Chocolate": load("res://assets/items/ingredient_chocolate.png"),
	"Cocoa": load("res://assets/items/ingredient_cocoa.png"),
	"Flour": load("res://assets/items/ingredient_flour.png"),
	"Sugar": load("res://assets/items/ingredient_sugar.png"),
	"Water": load("res://assets/items/ingredient_water.png"),
	"Cookie Dough": load("res://assets/items/ingredient_cookie_dough.png"),
	"Bread Dough": load("res://assets/items/ingredient_bread_dough.png"),
	"Risen Dough": load("res://assets/items/ingredient_risen_dough.png"),
	"Risen Dough (Banana)": load("res://assets/items/ingredient_risen_dough_banana.png"),
	"Risen Dough (Cheese)": load("res://assets/items/ingredient_risen_dough_cheese.png"),
	"Risen Dough (Coconut)": load("res://assets/items/ingredient_risen_dough_coconut.png"),
	"Risen Dough (Ube)": load("res://assets/items/ingredient_risen_dough_ube.png"),
	"Mush": load("res://assets/items/ingredient_mush.png"),
	"Cake Box": load("res://assets/items/item_cake_box.png"),
}
